### ISSUE TITLE
Typo in CountAndEchoDuckFactory

### ISSUE THREAD

**Issue by napatswift** [thewro11/cs471-DuckSimulator#1]
What a great repo! Thank you for this work.

But I found little typo here. I think you meant `new DuckCall()` not `new RedheadDuck()`

https://github.com/thewro11/cs471-DuckSimulator/blob/405e76f1cf3ca92f305bb5654c4699a01c6bdff9/src/me/thiti/factories/CountAndEchoDuckFactory.java#L22-L25

**Comment by thewro11** [comment]
That's an awful typo. Thank you for your PR! :D
